#pragma once
/*
 * LB_VGA_pins.h - board wiring.
 *
 * The 16 data lines carry one RGB565 pixel straight from the LCD_CAM peripheral
 * to the R2R ladder, so D0..D15 must map to the matching weight on the ladder:
 * D0..D4 = blue, D5..D10 = green, D11..D15 = red.
 *
 * Verified on hardware with examples/01_PinCheck (colour bars, gradients and the
 * 16 single-bit patches all correct).
 *
 * --- Using a different board ---
 * Do NOT edit this file. Every macro below is wrapped in #ifndef, so you can
 * override any of them from your sketch before including LB_VGA.h:
 *
 *     #define LB_VGA_PIN_HSYNC 40
 *     #define LB_VGA_PIN_VSYNC 41
 *     #define LB_VGA_PIN_DATA_INIT { 1,2,3,4,5, 6,7,8,9,10,11, 12,13,14,15,16 }
 *     #include <LB_VGA.h>
 *
 * ...or from build flags / boards.local.txt if you prefer.
 */

/* Sync polarity for VGA is negative: idle high, pulse low. */
#ifndef LB_VGA_PIN_HSYNC
#define LB_VGA_PIN_HSYNC 2
#endif

#ifndef LB_VGA_PIN_VSYNC
#define LB_VGA_PIN_VSYNC 1
#endif

/* D0..D15 = B0..B4, G0..G5, R0..R4 */
#ifndef LB_VGA_PIN_DATA_INIT
#define LB_VGA_PIN_DATA_INIT   \
  {                            \
    11, 12, 13, 14, 21,        \
    17, 18, 8, 3, 9, 10,       \
    7, 15, 16, 38, 39          \
  }
#endif

/*
 * Pins to avoid on this board:
 *   GPIO19/20   native USB D-/D+. This project logs over the on-board UART
 *               (GPIO43/44) instead: the native USB CDC wedges permanently
 *               after a firmware panic, and then neither esptool nor the
 *               serial monitor can reach the chip.
 *   GPIO33..37  octal PSRAM on N16R8 modules. Never use these.
 *   GPIO0/45/46 strapping pins, sampled at reset.
 */
