#!/usr/bin/env python3
"""
make_assets.py - turn any image into the photo_data.h that 07_Photo embeds.

    python3 make_assets.py <source-image> [WxH] [output.h]

    make_assets.py cat.jpg                                    -> 320x240 photo_data.h here
    make_assets.py cat.jpg 128x96 ../10_Dashboard/photo_small.h

It does three things:

  1. Scales the source to cover WxH (scale up until it covers, then centre-crop)
     using macOS's built-in sips, and saves it as a BASELINE JPEG.

  2. Verifies it really is baseline. LovyanGFX's decoder is TJpgDec-based and
     **cannot read progressive JPEGs** - it fails without reporting anything and
     you get a blank screen. The VGA Gallery project in this repository lost time
     to the same trap.

  3. Emits photo_data.h: a 16x16 RGB565 icon computed here (to show that an image
     is nothing but an array of numbers) plus the JPEG as a byte array, and
     prints the size comparison.

No libraries needed: sips ships with macOS, and the JPEG path only ever handles
raw bytes.
"""
import subprocess, sys, os, struct

HERE = os.path.dirname(os.path.abspath(__file__))
if len(sys.argv) < 2:
    sys.exit(__doc__.strip())
SRC = sys.argv[1]
W, H = (int(v) for v in sys.argv[2].split("x")) if len(sys.argv) > 2 else (320, 240)
TMP = "/tmp/lbvga_photo.jpg"
OUT = os.path.abspath(os.path.join(HERE, sys.argv[3])) if len(sys.argv) > 3 \
    else os.path.join(HERE, "photo_data.h")

# ---- 1. scale to cover, then centre-crop ----
subprocess.run(["cp", SRC, TMP], check=True)
w, h = [int(l.split(":")[1]) for l in subprocess.run(
    ["sips", "-g", "pixelWidth", "-g", "pixelHeight", TMP],
    capture_output=True, text=True).stdout.strip().split("\n")[1:3]]
if w / h > W / H:              # wider than the target: match height, crop sides
    subprocess.run(["sips", "--resampleHeight", str(H), TMP], check=True,
                   stdout=subprocess.DEVNULL)
else:                          # taller: match width, crop top and bottom
    subprocess.run(["sips", "--resampleWidth", str(W), TMP], check=True,
                   stdout=subprocess.DEVNULL)
subprocess.run(["sips", "-c", str(H), str(W), TMP], check=True, stdout=subprocess.DEVNULL)
subprocess.run(["sips", "-s", "format", "jpeg", "-s", "formatOptions", "70", TMP],
               check=True, stdout=subprocess.DEVNULL)

jpg = open(TMP, "rb").read()

# ---- 2. check for baseline ----
# SOF0 (0xFFC0) = baseline, SOF2 (0xFFC2) = progressive
i, sof = 2, None
while i < len(jpg) - 1:
    if jpg[i] != 0xFF:
        i += 1
        continue
    m = jpg[i + 1]
    if m in (0xC0, 0xC1, 0xC2, 0xC3):
        sof = m
        break
    if m in (0xD8, 0xD9) or 0xD0 <= m <= 0xD7:
        i += 2
        continue
    i += 2 + struct.unpack(">H", jpg[i + 2:i + 4])[0]
if sof is None:
    sys.exit("no SOF marker found - is this really a JPEG?")
if sof == 0xC2:
    sys.exit("PROGRESSIVE JPEG - the decoder cannot read it. Re-save as baseline.")
print(f"baseline JPEG confirmed (SOF marker 0x{sof:02X}), {len(jpg)} bytes")

# ---- 3. a 16x16 icon, computed, to show an image is just an array ----
def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

icon = []
for y in range(16):
    for x in range(16):
        dx, dy = x - 7.5, y - 7.5
        d = (dx * dx + dy * dy) ** 0.5
        if d > 7.5:
            icon.append(0)                       # outside the circle
        elif (dx * dx + (dy + 2) ** 2) ** 0.5 < 1.2 and abs(dx) > 1.5:
            icon.append(rgb565(20, 20, 20))      # eyes
        elif 4.0 < d < 5.2 and dy > 1.5:
            icon.append(rgb565(20, 20, 20))      # mouth
        else:
            icon.append(rgb565(255, 200, 40))    # face
assert len(icon) == 256

with open(OUT, "w") as f:
    f.write("/* Generated by make_assets.py - do not edit by hand.\n"
            "   Regenerate: python3 make_assets.py [source-image] [WxH] [output.h] */\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("/* A 16x16 icon, computed rather than loaded: an image is a run of\n"
            "   RGB565 numbers and nothing more. */\n")
    f.write("#define ICON_W 16\n#define ICON_H 16\n")
    f.write("static const uint16_t icon16[ICON_W * ICON_H] = {\n")
    for y in range(16):
        f.write("  " + ",".join(f"0x{v:04X}" for v in icon[y * 16:(y + 1) * 16]) + ",\n")
    f.write("};\n\n")
    f.write(f"/* A {W}x{H} photo as a baseline JPEG.\n")
    f.write(f"   Uncompressed the same image would be {W*H*2} bytes of RGB565;\n")
    f.write(f"   compressed it is {len(jpg)}. */\n")
    f.write(f"#define PHOTO_W {W}\n#define PHOTO_H {H}\n")
    f.write(f"#define PHOTO_RAW_BYTES {W*H*2}\n")
    f.write(f"#define PHOTO_JPG_LEN {len(jpg)}\n")
    f.write("static const uint8_t photo_jpg[PHOTO_JPG_LEN] = {\n")
    for i in range(0, len(jpg), 16):
        f.write("  " + ",".join(f"0x{b:02X}" for b in jpg[i:i + 16]) + ",\n")
    f.write("};\n")

print(f"wrote {OUT}")
print(f"size: raw RGB565 {W*H*2} bytes  vs  JPEG {len(jpg)} bytes "
      f"({W*H*2/len(jpg):.1f}x smaller)")
